### ISSUE TITLE
What am I doing wrong ?

### ISSUE THREAD

**Issue by Leninsky** [willwashburn/phpamo#1]
```
<?php
require  __DIR__ . '/vendor/autoload.php';

  $camo = new WillWashburn\Phpamo\Client();
  $camo->setDomain('https://mydomain.com/camoproxy/');
  $camo->setCamoKey('mycamokey');

  $test = $camo->proxy('someurl'); // returns the proxy url 

 print $test;
?>
```

When I run hhvm test.php it outputs : Fatal error: Class undefined: WillWashburn\Phpamo\Client in /usr/local/src/camotest/test.php on line 4

**Comment by willwashburn** [comment]
I just pushed up another version, I had the namespace wrong. Sorry if that wasted your time and thanks for the heads up!
